<?php

namespace Modules\Vehicle\Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;
use Modules\Vehicle\Models\VehicleModel;
use Modules\Vehicle\Models\VehicleBrand;

class VehicleModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $models = [
            [ "brand_id" => 1 , "ar" => 'اف جي ', "en" => 'Fj'],
            [ "brand_id" => 1 , "ar" => 'افالون ', "en" => 'Avalon'],
            [ "brand_id" => 1 , "ar" => 'اوريون ', "en" => 'Orion'],
            [ "brand_id" => 1 , "ar" => 'برادو ', "en" => 'Prado'],
            [ "brand_id" => 1 , "ar" => 'تويوتا 2000جي تي', "en" => 'Toyota 2000GT'],
            [ "brand_id" => 1 , "ar" => 'تويوتا 4 رنر', "en" => 'Toyota 4Runner'],
            [ "brand_id" => 1 , "ar" => 'تويوتا 7', "en" => 'Toyota 7'],
            [ "brand_id" => 1 , "ar" => 'تويوتا 86', "en" => 'Toyota 86'],
            [ "brand_id" => 1 , "ar" => 'تويوتا AE86', "en" => 'Toyota AE86'],
            [ "brand_id" => 1 , "ar" => 'تويوتا F3R', "en" => 'Toyota F3R'],
            [ "brand_id" => 1 , "ar" => 'تويوتا الفئة إس', "en" =>'Toyota S-Class'],
            [ "brand_id" => 1 , "ar" => 'تويوتا الفئة أ', "en" =>'Toyota A-Class'],
            [ "brand_id" => 1 , "ar" => 'تويوتا الفئة جي', "en" =>'Toyota G-Class'],
            [ "brand_id" => 1 , "ar" => 'تويوتا إف جيه كروزر', "en" =>'Toyota FJ Cruiser'],
            [ "brand_id" => 1 , "ar" => 'تويوتا إم آر 2', "en" => 'Toyota MR2'],
            [ "brand_id" => 1 , "ar" => 'تويوتا إنوفا', "en" => 'Toyota Innova'],
            [ "brand_id" => 1 , "ar" => 'تويوتا إي كوم', "en" =>'Toyota e.com'],
            [ "brand_id" => 1 , "ar" => 'تويوتا إيكو', "en" => 'Toyota Echo'],
            [ "brand_id" => 1 , "ar" => 'تويوتا أفالون', "en" => 'Toyota Avalon'],
            [ "brand_id" => 1 , "ar" => 'تويوتا أفانزا', "en" => 'Toyota Avanza'],
            [ "brand_id" => 1 , "ar" => 'تويوتا أفينسيس', "en" => 'Toyota Avensis'],
            [ "brand_id" => 1 , "ar" => 'تويوتا ألفارد', "en" => 'Toyota Alphard'],
            [ "brand_id" => 1 , "ar" => 'تويوتا أليون', "en" => 'Toyota Allion'],
            [ "brand_id" => 1 , "ar" => 'تويوتا أورس', "en" => 'Toyota urs'],
            [ "brand_id" => 1 , "ar" => 'تويوتا أوريون', "en" => 'Toyota Aurion'],
            [ "brand_id" => 1 , "ar" => 'تويوتا أوريون (إكس في 40)', "en" => 'Toyota Aurion (XV40)'],
            [ "brand_id" => 1 , "ar" => 'تويوتا أيجو', "en" => 'Toyota Aygo'],
            [ "brand_id" => 1 , "ar" => 'تويوتا آي-ريل', "en" =>'Toyota i-Rail'],
            [ "brand_id" => 1 , "ar" => 'تويوتا آي-سوينج', "en" =>'Toyota i-Swing'],
            [ "brand_id" => 1 , "ar" => 'تويوتا آي-فوت', "en" =>'Toyota i-Foot'],
            [ "brand_id" => 1 , "ar" => 'تويوتا آي-يونت', "en" =>'Toyota i-unit'],
            [ "brand_id" => 1 , "ar" => 'تويوتا آي كيو', "en" => 'Toyota iQ'],
            [ "brand_id" => 1 , "ar" => 'تويوتا بريفيا', "en" => 'Toyota Previa'],
            [ "brand_id" => 1 , "ar" => 'تويوتا بريميو', "en" => 'Toyota Premio'],
            [ "brand_id" => 1 , "ar" => 'تويوتا بليزارد', "en" => 'Toyota Blizzard'],
            [ "brand_id" => 1 , "ar" => 'تويوتا بوبليكا', "en" => 'Toyota Publica'],
            [ "brand_id" => 1 , "ar" => 'تويوتا بي إم', "en" => 'Toyota BMW'],
            [ "brand_id" => 1 , "ar" => 'تويوتا بي زد 4 أكس', "en" => 'Toyota BZ4X'],
            [ "brand_id" => 1 , "ar" => 'تويوتا تاكوما', "en" => 'Toyota Tacoma'],
            [ "brand_id" => 1 , "ar" => 'تويوتا تندرا', "en" => 'Toyota Tundra'],
            [ "brand_id" => 1 , "ar" => 'تويوتا تي100', "en" => 'Toyota T100'],
            [ "brand_id" => 1 , "ar" => 'تويوتا تيرسل', "en" => 'Toyota Tercel'],
            [ "brand_id" => 1 , "ar" => 'تويوتا داينا', "en" => 'Toyota Dyna'],
            [ "brand_id" => 1 , "ar" => 'تويوتا راف 4 اي في', "en" =>'Toyota RAV4 EV'],
            [ "brand_id" => 1 , "ar" => 'تويوتا راڤ4', "en" => 'Toyota Rav4'],
            [ "brand_id" => 1 , "ar" => 'تويوتا ستارليت', "en" => 'Toyota Starlet'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سليكا جي تي-فور', "en" => 'Toyota Celica GT-Four'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سنشري', "en" => 'Toyota Century'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سوارير', "en" => 'Toyota Soarer'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سوبرا', "en" => 'Toyota Supra'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سي + بود', "en" =>'Toyota C+Pod'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سي اتش ار', "en" => 'Toyota CHR'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سيكويا', "en" => 'Toyota Sequoia'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سيليكا', "en" => 'Toyota Celica'],
            [ "brand_id" => 1 , "ar" => 'تويوتا سيينا', "en" => 'Toyota Sienna'],
            [ "brand_id" => 1 , "ar" => 'تويوتا فنزا', "en" => 'Toyota Venza'],
            [ "brand_id" => 1 , "ar" => 'تويوتا فورتشنر', "en" => 'Toyota Fortuner'],
            [ "brand_id" => 1 , "ar" => 'تويوتا فيرسو', "en" => 'Toyota Verso'],
            [ "brand_id" => 1 , "ar" => 'تويوتا فيوس', "en" => 'Toyota Vios'],
            [ "brand_id" => 1 , "ar" => 'تويوتا ڤيتز', "en" => 'Toyota Vitz'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كارينا', "en" => 'Toyota Carina'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كالدينا', "en" => 'Toyota Caldina'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كامري', "en" => 'Toyota Camry'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كامري سولارا', "en" =>'Toyota Camry Solara'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كراون', "en" => 'Toyota Crown'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كريستا', "en" => 'Toyota Cresta'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كريسيدا', "en" => 'Toyota Cressida'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كلاسيك', "en" => 'Toyota Classic'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كورولا', "en" => 'Toyota Corolla'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كورونا', "en" => 'Toyota Corona'],
            [ "brand_id" => 1 , "ar" => 'تويوتا كوستر', "en" => 'Toyota Coaster'],
            [ "brand_id" => 1 , "ar" => 'تويوتا لاند كروزر', "en" =>'Toyota Land Cruiser'],
            [ "brand_id" => 1 , "ar" => 'تويوتا مارك 2', "en" =>'Toyota Mark 2'],
            [ "brand_id" => 1 , "ar" => 'تويوتا مارك إكس', "en" =>'Toyota Mark X'],
            [ "brand_id" => 1 , "ar" => 'تويوتا ميجا كروزر', "en" =>'Toyota Mega Cruiser'],
            [ "brand_id" => 1 , "ar" => 'تويوتا ميراي', "en" => 'Toyota Mirai'],
            [ "brand_id" => 1 , "ar" => 'تويوتا نوح', "en" => 'Toyota Noah'],
            [ "brand_id" => 1 , "ar" => 'تويوتا هايس', "en" => 'Toyota Hiace'],
            [ "brand_id" => 1 , "ar" => 'تويوتا هايلاندر', "en" => 'Toyota Highlander'],
            [ "brand_id" => 1 , "ar" => 'تويوتا هايلوكس', "en" => 'Toyota Hilux'],
            [ "brand_id" => 1 , "ar" => 'تويوتا ويش', "en" => 'Toyota Wish'],
            [ "brand_id" => 1 , "ar" => 'تويوتا يارس', "en" => 'Toyota Yaris'],
            [ "brand_id" => 1 , "ar" => 'تويوتا يارس كروس', "en" =>'Toyota Yaris Cross'],
            [ "brand_id" => 1 , "ar" => 'ربع ', "en" => 'a fourth'],
            [ "brand_id" => 1 , "ar" => 'شاص ', "en" => 'Shas'],
            [ "brand_id" => 1 , "ar" => 'فورتشنر', "en" => 'Fortuner'],
            [ "brand_id" => 1 , "ar" => 'كامري ', "en" => 'Camry'],
            [ "brand_id" => 1 , "ar" => 'كراون ', "en" => 'Crown'],
            [ "brand_id" => 1 , "ar" => 'كورولا ', "en" => 'Corolla'],
            [ "brand_id" => 1 , "ar" => 'لاندكروزر ', "en" => 'Land Cruiser'],
            [ "brand_id" => 1 , "ar" => 'هايلكس ', "en" => 'Hilux'],
            [ "brand_id" => 1 , "ar" => 'يارس ', "en" => 'Yaris'],


            ["brand_id" => 2 ,"ar" => 'ابيكا', "en" => 'Epica'],
            ["brand_id" => 2 ,"ar" => 'افيو ', "en" => 'Aveo'],
            ["brand_id" => 2 ,"ar" => 'امبالا ', "en" => 'Impala'],
            ["brand_id" => 2 ,"ar" => 'اوبترا', "en" => 'Optra'],
            ["brand_id" => 2 ,"ar" => 'تاهو ', "en" => 'Tahoe'],
            ["brand_id" => 2 ,"ar" => 'سبارك ', "en" => 'Spark'],
            ["brand_id" => 2 ,"ar" => 'سلفرادو', "en" => 'Silverado'],
            ["brand_id" => 2 ,"ar" => 'سوبربان ', "en" => 'Superman'],
            ["brand_id" => 2 ,"ar" => 'كابرس ', "en" => 'Caprice'],
            ["brand_id" => 2 ,"ar" => 'كروز ', "en" => 'Cruz'],
            ["brand_id" => 2 ,"ar" => 'كمارو ', "en" => 'Camaro'],
            ["brand_id" => 2 ,"ar" => 'كورفت', "en" => 'Corvette'],
            ["brand_id" => 2 ,"ar" => 'لومينا ', "en" => 'Lumina'],
            ["brand_id" => 2 ,"ar" => 'ماليبو', "en" => 'Malibu'],


            ["brand_id" => 3 ,"ar" => 'اكس تريل', "en" => 'X-trail'],
            ["brand_id" => 3 ,"ar" => 'التيما ', "en" => 'Altima'],
            ["brand_id" => 3 ,"ar" => 'باترول ', "en" => 'Patrol'],
            ["brand_id" => 3 ,"ar" => 'باثفندر ', "en" => 'Pathfinder'],
            ["brand_id" => 3 ,"ar" => 'سنترا ', "en" => 'Centra'],
            ["brand_id" => 3 ,"ar" => 'صني ', "en" => 'Sunny'],
            ["brand_id" => 3 ,"ar" => 'مكسيما ', "en" => 'Maxima'],



            ["brand_id" => 4 , "ar" => '‏H-1', "en" => 'H-1'],
            ["brand_id" => 4 , "ar" => 'ازيرا', "en" => 'Azira'],
            ["brand_id" => 4 , "ar" => 'اكسنت ', "en" => 'Accent'],
            ["brand_id" => 4 , "ar" => 'النترا ', "en" => 'Elantra'],
            ["brand_id" => 4 , "ar" => 'توسان ', "en" => 'Toussaint'],
            ["brand_id" => 4 , "ar" => 'سنتافي', "en" => 'Santa Fe'],
            ["brand_id" => 4 , "ar" => 'سوناتا ', "en" => 'Sonata'],
            ["brand_id" => 4 , "ar" => 'فيلوستر', "en" => 'Veloster'],
            ["brand_id" => 4 , "ar" => 'كريتا ', "en" => 'Krita'],
            ["brand_id" => 4 , "ar" => 'كونا ', "en" => 'KONA'],


            ["brand_id" => 5 ,"ar" => 'S', "en" => '‏S '],
            ["brand_id" => 5 ,"ar" => 'E', "en" => '‏E'],
            ["brand_id" => 5 ,"ar" => 'سي', "en" => '‏Se'],
            ["brand_id" => 5 ,"ar" => '‏Sel', "en" => '‏Sel'],
            ["brand_id" => 5 ,"ar" => '‏Amg', "en" => '‏Amg'],
            ["brand_id" => 5 ,"ar" => 'المركبات السياحية', "en" => 'Tourer Vehicles '],
            ["brand_id" => 5 ,"ar" => 'شد الوجه فيتو تورير', "en" => 'Vito Tourer Facelift'],
            ["brand_id" => 5 ,"ar" => 'سبرينتر تورير', "en" => 'Sprinter Tourer'],
            ["brand_id" => 5 ,"ar" => 'الحافلات الصغيرة', "en" => 'Mini Buses'],
            ["brand_id" => 5 ,"ar" => 'الحافلة المكوكية سبرينتر', "en" => 'Sprinter Shuttle Bus'],
            ["brand_id" => 5 ,"ar" => 'حافلات ميتسوبيشي فوزو', "en" => 'Mitsubishi FUSO Buses'],
            ["brand_id" => 5 ,"ar" => 'فوزو روزا', "en" => 'FUSO ROSA '],
            ["brand_id" => 5 ,"ar" => 'أبواب خلفية لحافلة ROSA', "en" =>  'ROSA Bus rear doors'],
            ["brand_id" => 5 ,"ar" => 'حافلات إم سي في', "en" => 'MCV Buses'],
            ["brand_id" => 5 ,"ar" => 'ام سي في 260', "en" => 'MCV 260'],
            ["brand_id" => 5 ,"ar" => 'ام سي في 400', "en" => 'MCV 400'],
            ["brand_id" => 5 ,"ar" => 'ام سي في 500', "en" => 'MCV 500'],
            ["brand_id" => 5 ,"ar" => 'ام سي في 600', "en" => 'MCV 600'],
            ["brand_id" => 5 ,"ar" => 'حافلات مرسيدس بنز', "en" =>'Mercedes Benz Buses'],
            ["brand_id" => 5 ,"ar" => 'الحافلات السياحية', "en" => 'BUSES Tourismo'],
            ["brand_id" => 5 ,"ar" => 'ترافيجو باص', "en" => 'Travego BUS'],

            ["brand_id" => 6 ,"ar" => 'اكورد', "en" => 'Accord'],
            ["brand_id" => 6 ,"ar" => 'سيفيك', "en" => 'Civic'],


            ["brand_id" => 7 ,"ar" => 'اوبتيما', "en" => 'Optima'],
            ["brand_id" => 7 ,"ar" => 'كيا بيكانتو', "en" => 'Kia Picanto'],
            ["brand_id" => 7 ,"ar" => 'كيا تيلورايد', "en" => 'Kia Telluride'],
            ["brand_id" => 7 ,"ar" => 'كيا جويس', "en" => 'Kia Joyce'],
            ["brand_id" => 7 ,"ar" => 'كيا ريو', "en" => 'Kia Rio'],
            ["brand_id" => 7 ,"ar" => 'كيا سبكترا', "en" => 'Kia Spectra'],
            ["brand_id" => 7 ,"ar" => 'كيا سبورتاج', "en" => 'Kia Sportage'],
            ["brand_id" => 7 ,"ar" => 'كيا ستنغر', "en" => 'Kia Stinger'],
            ["brand_id" => 7 ,"ar" => 'كيا سورنتو', "en" => 'Kia Sorento'],
            ["brand_id" => 7 ,"ar" => 'كيا سيراتو', "en" => 'Kia Cerato'],
            ["brand_id" => 7 ,"ar" => 'كيا سيفيا', "en" => 'Kia Sephia'],
            ["brand_id" => 7 ,"ar" => 'كيا كادينزا', "en" => 'Kia Cadenza'],
            ["brand_id" => 7 ,"ar" => 'كيا كي5', "en" => 'Kia K5'],


            ["brand_id" => 8 ,"ar" => '‏®SRT هيلكات وايد بودي', "en" => 'SRT® Hellcat Widebody'],
            ["brand_id" => 8 ,"ar" => '‏GT.', "en" => '‏GT.'],
            ["brand_id" => 8 ,"ar" => '‏R/T سكات باك وايد بودي', "en" =>  'R/T Scat Pack Wide Body'],
            ["brand_id" => 8 ,"ar" => '‏R/T.', "en" => 'R/T.'],
            ["brand_id" => 8 ,"ar" => 'إس آر تي® هيلكات رد آي وايد بودي', "en" =>'SRT® Hellcat Red Eye Wide Body'],
            ["brand_id" => 8 ,"ar" => 'دوج كرافان', "en" => 'Dodge caravan'],
            ["brand_id" => 8 ,"ar" => 'دودج تشارجر', "en" => 'Dodge Charger'],
            ["brand_id" => 8 ,"ar" => 'دودج تشارجر (2005)', "en" => 'Dodge Charger (2005)'],
            ["brand_id" => 8 ,"ar" => 'دودج جيرني', "en" => 'Dodge Journey'],
            ["brand_id" => 8 ,"ar" => 'دودج دايناستي', "en" => 'Dodge Dynasty'],
            ["brand_id" => 8 ,"ar" => 'دودج رام', "en" => 'Dodge Ram'],
            ["brand_id" => 8 ,"ar" => 'دودج رام فان', "en" => 'Dodge Ram Van'],
            ["brand_id" => 8 ,"ar" => 'دودج شالنجر', "en" => 'Dodge Challenger'],
            ["brand_id" => 8 ,"ar" => 'دودج فايبر', "en" => 'Dodge Viper'],
            ["brand_id" => 8 ,"ar" => 'دورانجو ', "en" => 'Durango'],

            ["brand_id" => 9 ,"ar" => 'مازدا 6.', "en" => 'Mazda 6.'],
            ["brand_id" => 9 ,"ar" => 'مازدا CX-3.', "en" =>'Mazda CX-3.'],
            ["brand_id" => 9 ,"ar" => 'مازدا CX-30.', "en" =>'Mazda CX-30.'],
            ["brand_id" => 9 ,"ar" => 'مازدا CX-5.', "en" =>'Mazda CX-5.'],
            ["brand_id" => 9 ,"ar" => 'مازدا CX-9', "en" =>'Mazda CX-9'],


            ["brand_id" => 10 ,"ar" => 'فورد f350 كنج رانش ', "en" => 'Ford f350 king ranch'],
            ["brand_id" => 10 ,"ar" => 'فورد اكسبديشن ', "en" => 'Ford Expedition'],
            ["brand_id" => 10 ,"ar" => 'فورد توروس', "en" => 'Ford Taurus'],
            ["brand_id" => 10 ,"ar" => 'فورد كراون فيكتوريا ', "en" => 'Ford Crown Victoria'],
            ["brand_id" => 10 ,"ar" => 'لنكولن تاون كار ', "en" => 'Lincoln Town Car'],
            ["brand_id" => 10 ,"ar" => 'ميركوري جراند ماركيز ', "en" => 'Mercury Grand Marquis'],


            ["brand_id" => 11 ,"ar" => 'بي إم دبليو أم 1', "en" => 'BMW M1'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو أم 3', "en" => 'BMW M3'],
            ["brand_id" => 11 ,"ar" => 'بي أم دبليو أم 4', "en" => 'BMW M4'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو أم 5', "en" => 'BMW M5'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو أم 6', "en" => 'BMW M6'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو أم كوبيه', "en" => 'M Coupe'],
            ["brand_id" => 11 ,"ar" => 'بي أم دبليو الفئة أكس', "en" => 'X-Series'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو إكس1', "en" => 'BMW X1'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو إكس2', "en" => 'BMW X2'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو إكس3', "en" => 'BMW X3'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو أكس3 أف25', "en" => 'BMW X3 F25'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو إكس4', "en" => 'BMW X4'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو اكس 5 (اف 15)', "en" => 'BMW X5 (F15)'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو اكس 5 (اي 53)', "en" => 'BMW X5 (E53)'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو اكس 5 (اي 70) ', "en" => 'BMW X5 (i70)'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو إكس6', "en" => 'BMW X6'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو إم رودستر', "en" => 'BMW Roadster'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو آي', "en" => 'BMW i'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو آي 3', "en" => 'BMW i3'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو إي9', "en" => 'BMW E9'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو الفئة الأولى', "en" => 'BMW 1 Series'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو الفئة الثالثة', "en" => 'BMW 3 Series'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو الفئة الخامسة', "en" => 'BMW fifth category'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو الفئة 5 (E28)',  "en" => 'BMW 5 Series (E28)'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو الفئة السادسة', "en" => 'BMW 6 Series'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو الفئة السابعة', "en" => 'BMW 7 Series'],
            ["brand_id" => 11 ,"ar" => 'ي إم دبليو النسخة 7 (إي32)', "en" => 'BMW Edition 7 (E32)'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو الفئة الثامنة', "en" => 'BMW 8 Series'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو 507', "en" => 'BMW 507'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو زد 1', "en" => 'BMW Z1'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو زد 4 (أي 85)', "en" => 'BMW Z4 (i85)'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو زد 4 (أي 89)', "en" => 'BMW Z4 (i89)'],
            ["brand_id" => 11 ,"ar" => 'بي إم دبليو زد 8 (أي 52)', "en" => 'BMW Z8 (A52)'],

        ];


        foreach ($models as $model) {
            VehicleModel::create([
                "vehicle_brand_id" => $model["brand_id"],
                "capacity" => 4,
                "name" => [
                    "en" =>   $model["en"],
                    "ar" =>   $model["ar"]
                ]
            ]);
        }
    }
}
